import type { Metadata } from "next";
import "../styles/globals.scss";
import StoreProvider from "../containers/StoreProvider";
import { Container } from "react-bootstrap";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>
          <Container>{children}</Container>
        </body>
      </html>
    </StoreProvider>
  );
}
